"""init

Revision ID: 352c62e2b469
Revises: 
Create Date: 2024-10-07 17:24:43.615194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352c62e2b469'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshops', sa.Column('name_short', sa.String(length=30), nullable=False))
    op.add_column('workshops', sa.Column('rut', sa.String(length=20), nullable=True))
    op.add_column('workshops', sa.Column('address', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshops', 'address')
    op.drop_column('workshops', 'rut')
    op.drop_column('workshops', 'name_short')
    # ### end Alembic commands ###
